"""List of API Enpoints the moco wrapper knows about."""

API_PATH = {
    "company_create":           "/companies",
    "company_update":           "/companies/{id}",
    "company_get":              "/companies/{id}",
    "company_getlist":          "/companies",
    "project_getlist":          "/projects",
    "project_get":              "/projects/{id}",
    "project_assigned":         "/projects/assigned",
    "project_create":           "/projects",
    "project_update":           "/projects/{id}",
    "project_archive":          "/projects/{id}/archive",
    "project_unarchive":        "/projects/{id}/unarchive",
    "project_report":           "/projects/{id}/report",
    "project_contract_getlist": "/projects/{project_id}/contracts",
    "project_contract_get":     "/projects/{project_id}/contracts/{contract_id}",
    "project_contract_create":  "/projects/{project_id}/contracts",
    "project_contract_update":  "/projects/{project_id}/contracts/{contract_id}",
    "project_contract_delete":  "/projects/{project_id}/contracts/{contract_id}",
    "contact_getlist":          "/contacts/people",
    "contact_get":              "/contacts/people/{id}",
    "contact_create":           "/contacts/people",
    "contact_update":           "/contacts/people/{id}",
    "comment_create":           "/comments",
    "comment_update":           "/comments/{id}",
    "comment_getlist":          "/comments",
    "comment_get":              "/comments/{id}",
    "comment_create_bulk":      "/comments/bulk",
    "comment_delete":           "/comments/{id}",
    "unit_get":                 "/units/{id}",
    "unit_getlist":             "/units",
    "user_get":                 "/users/{id}",
    "user_getlist":             "/users",
    "user_create":              "/users",
    "user_update":              "/users/{id}",
    "user_delete":              "/users/{id}"
}